### ISSUE TITLE
Quickstart Fail

### ISSUE THREAD

**Issue by DLPQ** [qiskit-community/qiskit-aqt-provider#121]
### Informations

- **Qiskit AQT Provider version**: qiskit-aqt-provider==1.1.0
- **Python version**: 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]
- **Operating system**: Windows 10

### What is the current behavior?

Using the script from [https://qiskit-community.github.io/qiskit-aqt-provider/index.html](url) I get the following error:

ValueError: Operation ‘cx’ not in the basis gate set: {rz, r, rxx}

### Steps to reproduce the problem
Running the script.

### What is the expected behavior?
Expected output is a dictionary with a quasi-probability distribution, for example: {3: 0.57, 0: 0.43}

### Suggested solutions
I have no idea where this comes from. Using the aer-simulator instead works perfectly fine.

Using` result=qiskit.execute(circuit, backend).result()` instead of `result = sampler.run(circuit).result()` worked for me.

**Comment by fg-aqt** [comment]
I have a hard time reproducing your issue (although on Linux). Can you please provide more information?
- Did you install the qiskit-aqt-provider in an empty python environment?
  - If not, can you try to install the qiskit-aqt-provider in a fresh environment and see if the problem still occurs?
- What other qiskit libraries do you have installed and which versions?

**Comment by fg-aqt** [comment]
We can now say that the problems are Windows specific and we are investigating further. 

In the mean-time you should be able to run your code without problems if you have access to a Linux system or run Linux on Windows with WSL.

**Comment by DLPQ** [comment]
Can confirm, no problems under Linux.

**Comment by airwoodix** [comment]
Thanks for the bug report! The issue stems from varying behavior between Windows and Linux in the [`Decompose`](https://docs.quantum.ibm.com/api/qiskit/qiskit.transpiler.passes.Decompose) transpilation pass. It'll be fixed by #123, which we'll release in the next days.
