### ISSUE TITLE
Remove usage of deprecated qiskit.execute function

### ISSUE THREAD

**Issue by airwoodix** [qiskit-community/qiskit-aqt-provider#134]
The [`qiskit.execute`](https://docs.quantum.ibm.com/api/qiskit/execute) was deprecated in Qiskit [0.46.0](https://github.com/Qiskit/qiskit/releases/tag/0.46.0). See qiskit/qiskit#7892 for the background discussion. Replacement is either `backend.run(transpile(...), ...)` or using the `Sampler` primitive.

**Comment by G3mha** [comment]
For those who have not yet identified an alternative to the `execute()` method in their code, the simplest solution to maintain your code operational is to downgrade qiskit's installation. This can be achieved by first uninstalling qiskit on pip, and then executing `pip install qiskit==0.46.1`. By doing so, you will still have access to the `execute()` method.
