### ISSUE TITLE
docs: point to new qiskit inventory

### ISSUE THREAD

**Issue by airwoodix** [qiskit-community/qiskit-aqt-provider#138]
In #135, the link to the intersphinx inventory for Qiskit was updated from https://qiskit.org/documentation/ to https://docs.quantum.ibm.com/api/qiskit/. However, the latter points to Qiskit [1.0.0](https://github.com/Qiskit/qiskit/releases/tag/1.0.0) documentation, which breaks the build (see e.g. [this job](https://github.com/qiskit-community/qiskit-aqt-provider/actions/runs/7932206557/job/21658141451)).

Therefore, #136 points again to qiskit.org, which still serves the inventory for Qiskit 0.45.

@Eric-Arellano is the inventory for Qiskit <1 served by docs.quantum.ibm.com? I tried https://docs.quantum.ibm.com/api/qiskit/0.46/objects.inv but it doesn't point anywhere.

In the mid term, porting to Qiskit 1.0.0 will solve this issue.

**Comment by Eric-Arellano** [comment]
Thanks for opening this! I opened https://github.com/Qiskit/documentation/issues/829 and will try to get this out today.

**Comment by Eric-Arellano** [comment]
https://docs.quantum.ibm.com/api/qiskit/0.46/objects.inv is now live. Thanks for the feature request! That's really helpful for us to prioritize.

**Comment by airwoodix** [comment]
Fantastic! Thanks a lot @Eric-Arellano.
