### ISSUE TITLE
The RXXGate tranpiles to RXX-wrapped

### ISSUE THREAD

**Issue by jadersantos** [qiskit-community/qiskit-aqt-provider#144]
### Informations

- **Qiskit AQT provider version**: qiskit-aqt-provider =  1.30.0
- **Qiskit version**: qiskit = 0.46.0
- **Python version**: 3.12.1 (specified environment)
- **Operating system**: macOS : Sonoma 14.2.1

### What is the current behavior?
We have noticed an issue in transpiling a circuit with the gate rxx with optimization_level = 0. 
By using an argument theta outside the range [0,pi), the rxx gate is transpiled to rxx-wrapped, which is not in the basis gate set.
The problem could be overcome by using optimization_level > 0, but it shouldnt happen on the optimization_level =0 case. 

### Steps to reproduce the problem
```
from qiskit import QuantumCircuit, transpile
from qiskit_aqt_provider import AQTProvider
from qiskit_aqt_provider.primitives import AQTSampler

provider = AQTProvider("ACCESS_TOKEN")
backend = provider.get_backend("offline_simulator_no_noise")

circuit = QuantumCircuit(2)
circuit.rxx(-0.1, 0 ,1) ##the first argument is theta (we set it as negative to show the issue)
circuit_t = transpile(circuit, backend, optimization_level=0)
circuit_t.draw()
```

This code results with the wrapped-RXX gate. When attempting to run the circuit with said gate, the run results with an error:
```
job = backend.run(circuit_t,shots = 100)
```
" ValueError: Operation 'Rxx-warpped(-0.1)' npt om tje nasos gate set: {rz, r, rxxx}"

### What is the expected behavior?
With this basic script, the transpilation should've result in a circuit with gates which are in the basis gate set.

### Suggested solutions
-

**Comment by airwoodix** [comment]
Thanks for the bug report. The issue should be resolved by #145.
