### ISSUE TITLE
Attribute Errors in Algorithms from Qiskit-Aqua

### ISSUE THREAD

**Issue by czachow** [qiskit-community/qiskit-aqt-provider#20]
### Informations

- qiskit 0.19.6
- qiskit-aqt-provider: 0.2.0
- python: 3.7.6
- macOS: 10.15.6

### What is the current behavior?

The module qiskit-aqua currently requires different attributes in terms of backend configuration and job configuration to be set. Otherwise an error is produced.  

### Steps to reproduce the problem

Run quantum algorithm like VQE on AQT backend. 

### What is the expected behavior?

No errors

### Suggested solutions

Follow changes in issue https://github.com/Qiskit/qiskit-aqua/issues/1030 or implement solution in provider here.
I suggest a quick fix in the code here and will be working on it.

**Comment by mtreinish** [comment]
Fixed by #21
