### ISSUE TITLE
Get backend is missing

### ISSUE THREAD

**Issue by mtreinish** [qiskit-community/qiskit-aqt-provider#27]
### Informations

- **Qiskit AQT Provider version**: Master
- **Python version**: Any
- **Operating system**: Any

### What is the current behavior?

In #24 we lost the get_backend() method. This used to be provided for us by inheriting from the abstract provider class:

https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/providers/provider.py#L35

### Steps to reproduce the problem

Try to use get_backend()

### What is the expected behavior?

It works

### Suggested solutions

Add back that method (and `__eq__` which was also lost) to the AQTProvider class.

**Comment by nonhermitian** [comment]
Ok, let me add it back with a test
