### ISSUE TITLE
Documentation on qiskit.org/ecosystem is outdated

### ISSUE THREAD

**Issue by fg-aqt** [qiskit-community/qiskit-aqt-provider#88]
Picking up a topic that came up in an already closed issue:

>> Let me know if you need help from a qiskit-community admin.
>
>Your help would be very much appreciated, to be more specific:
>1. Would it be possible to redirect to the new documentation from https://qiskit.org/ecosystem/aqt/ ?
>2. We noticed that searching for "AQT" on https://qiskit.org/ecosystem does not return any results. What can we do so that the >Qiskit AQT Provider can be found there?

_Originally posted by @fg-aqt in https://github.com/qiskit-community/qiskit-aqt-provider/issues/60#issuecomment-1735868395_

**Comment by fg-aqt** [comment]
@1ucian0 I hope it was not inappropriate for me to assign the issue to you. If it was, I apologize and ask you to please let me know how best to proceed or who to get in touch with.

**Comment by airwoodix** [comment]
@frankharkins Documentation for this project was previously pushed to https://qiskit.org/ecosystem/aqt using [this script](https://github.com/qiskit-community/qiskit-aqt-provider/blob/d3420c1772954c89333a17368ed174a73d631499/tools/deploy_documentation.sh).
This is now obsolete (the documentation is this project's Github pages) but some people apparently still have a link to the old location (there should not be any links left on public pages). Would it be possible to make https://qiskit.org/ecosystem/aqt point nowhere? Thanks!

**Comment by fg-aqt** [comment]
>2. We noticed that searching for "AQT" on https://qiskit.org/ecosystem does not return any results. What can we do so that the >Qiskit AQT Provider can be found there?

Was already solved with https://github.com/qiskit-community/ecosystem/pull/563

**Comment by frankharkins** [comment]
@airwoodix sorry for the slow response. I've worked out how to redirect the link; should I redirect https://qiskit.org/ecosystem/aqt to https://qiskit-community.github.io/qiskit-aqt-provider/, or would you rather it 404?

**Comment by airwoodix** [comment]
@frankharkins thanks for your feedback! If a redirect is possible, then it's probably the nicest way to transition. But it wouldn't be a problem if that link would error with 404 in the future.

**Comment by Eric-Arellano** [comment]
Thanks @airwoodix! We have a PR set up with our internal infrastructure to set up the redirect as you're requesting.

**Comment by airwoodix** [comment]
Fantastic! Thanks @Eric-Arellano and @frankharkins! I'll close on first observation of the redirect :)
